# Generated by Django 6.0.1 on 2026-02-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurulüyeleri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurulüyeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sıra', models.CharField(max_length=2)),
                ('AdiSoyadi', models.CharField(max_length=50)),
                ('Mevki', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Talebe',
        ),
    ]
